AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
