#!/usr/bin/env node

/**
 * YouTube Video Extractor using Puppeteer
 *
 * Uses a headless browser to navigate to YouTube, then extracts cookies
 * for yt-dlp to use. This bypasses bot detection by establishing a real
 * browser session first.
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const fs = require('fs');

// Add stealth plugin to avoid detection
puppeteer.use(StealthPlugin());

// Get URL and cookie output path from command line arguments
const videoUrl = process.argv[2];
const cookieFile = process.argv[3] || '/tmp/youtube_cookies.txt';

if (!videoUrl) {
  console.error(JSON.stringify({ error: 'No URL provided' }));
  process.exit(1);
}

(async () => {
  let browser;

  try {
    // Launch headless browser with stealth mode
    browser = await puppeteer.launch({
      headless: 'new',
      executablePath: '/usr/bin/chromium',
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--disable-blink-features=AutomationControlled',
        '--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
      ]
    });

    const page = await browser.newPage();

    // Set viewport to look like a desktop browser
    await page.setViewport({ width: 1920, height: 1080 });

    // Set additional headers to look more like a real browser
    await page.setExtraHTTPHeaders({
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Linux"'
    });

    // Navigate to YouTube video
    console.error('Navigating to YouTube...');
    await page.goto(videoUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });

    // Wait a bit for any bot detection checks
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Wait for video player to start loading
    await page.waitForSelector('#movie_player, video', { timeout: 15000 });
    console.error('Video player detected');

    // Get cookies from the browser session
    const cookies = await page.cookies();

    // Convert cookies to Netscape format for yt-dlp
    let cookieContent = '# Netscape HTTP Cookie File\n';
    cookieContent += '# This file is generated by Puppeteer. Do not edit.\n\n';

    for (const cookie of cookies) {
      const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
      const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path;
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      // Handle session cookies (expires -1) and invalid expirations
      let expiration = '0';
      if (cookie.expires && cookie.expires > 0) {
        expiration = Math.round(cookie.expires).toString();
      }
      const name = cookie.name;
      const value = cookie.value;

      cookieContent += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
    }

    // Write cookies to file
    fs.writeFileSync(cookieFile, cookieContent);
    console.error(`Cookies saved to ${cookieFile}`);

    // Extract title from page
    const title = await page.title();

    await browser.close();

    // Output success
    console.log(JSON.stringify({
      success: true,
      title: title.replace(' - YouTube', ''),
      cookieFile: cookieFile
    }));
  } catch (error) {
    if (browser) {
      await browser.close();
    }
    console.error(JSON.stringify({ error: error.message, stack: error.stack }));
    process.exit(1);
  }
})();
